Repository morning-night-guild/platform-app, pull requests merged in 2023-03, with the labels that each got.

#39 chore(#38) 金曜夜に自動デプロイが実行されるように条件を設定
  .github/workflows/container.deploy.yaml
Labels: chore

#45 #44 ディレクトリ構造をリファクタリング
  README.md
  cmd/appapi/main.go
  cmd/appcore/main.go
  internal/adapter/controller/article.go
  internal/adapter/external/article.go
  internal/adapter/external/connect.go
  internal/adapter/external/health.go
  internal/adapter/gateway/article.go
  internal/adapter/gateway/article_test.go
  internal/adapter/handler/article.go
  internal/adapter/handler/article_test.go
  internal/adapter/handler/handler.go
  internal/adapter/handler/handler_test.go
  internal/adapter/handler/helth.go
  internal/adapter/handler/helth_test.go
  internal/domain/model/article/url.go
  internal/domain/repository/api_article.go
  internal/domain/repository/article.go
  internal/domain/repository/core_article.go
  internal/domain/repository/repository_test.go
  internal/domain/rpc/article.go
  internal/domain/rpc/health.go
  internal/domain/value/index.go
  internal/domain/value/index_test.go
  internal/domain/value/next_token.go
  internal/domain/value/next_token_test.go
  internal/domain/value/size.go
  internal/domain/value/size_test.go
  internal/driver/config/api.go
  internal/driver/config/core.go
  internal/driver/connect/client.go
  internal/driver/http/http.go
  internal/driver/postgres/postgres.go
  internal/driver/server/server.go
  internal/usecase/interactor/api_article_list.go
  internal/usecase/interactor/api_article_list_test.go
  internal/usecase/interactor/api_article_share.go
  internal/usecase/interactor/api_article_share_test.go
  internal/usecase/interactor/api_health_check.go
  internal/usecase/interactor/api_health_check_test.go
  internal/usecase/interactor/core_list.go
  internal/usecase/interactor/core_list_test.go
  internal/usecase/interactor/core_share.go
  internal/usecase/interactor/core_share_test.go
  internal/usecase/mock/api_health.go
  internal/usecase/mock/core_article.go
  internal/usecase/mock/repository_article.go
  internal/usecase/mock/rpc_article.go
  internal/usecase/mock/rpc_health.go
  internal/usecase/port/api_article.go
  internal/usecase/port/core_article.go
Labels: refactor

#50 #49 renovate発火時に依存関係をCIにて更新するように設定
  .github/workflows/auto.go.mod.yaml
  .github/workflows/auto.pr.merge.yaml
Labels: renovate

#52 #51 データ移行スクリプトを実装
  cmd/db2db/entrypoint.sh
  cmd/db2db/main.go
  cmd/migrate/main.go
Labels: feat

#61 #60 migrateとbackupコンテナを実装
  .docker/app/api/Dockerfile
  .docker/app/core/Dockerfile
  .docker/db/backup/Dockerfile
  .docker/db/migrate/Dockerfile
  .docker/docker-compose.yaml
  .env.local
  .github/workflows/container.build.yaml
  .github/workflows/container.deploy.yaml
  .github/workflows/document.yaml
  .github/workflows/test.e2e.yaml
  .github/workflows/vulnerability.yaml
  Makefile
  aqua.yaml
  cmd/app/api/.ko.yaml
  cmd/app/api/main.go
  cmd/app/core/.ko.yaml
  cmd/app/core/main.go
  cmd/db/backup/.ko.yaml
  cmd/db/backup/main.go
  cmd/db/db2db/entrypoint.sh
  cmd/db/db2db/main.go
  cmd/db/migrate/.ko.yaml
  cmd/db/migrate/main.go
Labels: feat

#64 #60 ローカルDBに接続するコマンドを追加
  Makefile
Labels: chore

#65 #60 配列宣言を修正
  cmd/db/backup/main.go
Labels: fix

#66 #60 repository dispatchの設定を修正
  .github/workflows/container.deploy.yaml
Labels: chore

#67 #60 不要なファイルを削除
  cmd/db/db2db/entrypoint.sh
  cmd/db/db2db/main.go
Labels: chore

#81 #80 オートマージ対象ブランチ名を修正
  .github/workflows/auto.pr.merge.yaml
Labels: bug

#78 #77 external層をリファクタリング
  cmd/app/api/main.go
  internal/adapter/external/article.go
  internal/adapter/external/connect.go
  internal/adapter/external/health.go
  internal/driver/connect/client.go
  internal/driver/connect/connect.go
Labels: refactor

#84 chore(aqua): replace the local Registry to the Stanard Registry
  aqua.yaml
  registry.yaml
Labels: chore

#92 #91 nancyコマンドを修正
  .github/workflows/vulnerability.yaml
  Makefile
Labels: chore, bug

#100 #98 認証機能のAPIを追加
  api/openapi.yaml
  e2e/appapi/article/list_test.go
  e2e/appapi/article/share_test.go
  internal/adapter/handler/article.go
  internal/adapter/handler/article_test.go
  internal/adapter/handler/auth.go
  internal/adapter/handler/helth.go
  pkg/openapi/client.gen.go
  pkg/openapi/server.gen.go
  pkg/openapi/types.gen.go
Labels: feat
