Repository morning-night-guild/platform-app, pull requests merged in 2023-04, with the labels that each got.

#113 #112 liveness用のエンドポイントを実装
  e2e/appapi/health/check_test.go
  e2e/appcore/health/check_test.go
  go.mod
  go.sum
  internal/driver/http/http.go
  vendor/github.com/bufbuild/connect-grpchealth-go/.gitignore
  vendor/github.com/bufbuild/connect-grpchealth-go/.golangci.yml
  vendor/github.com/bufbuild/connect-grpchealth-go/LICENSE
  vendor/github.com/bufbuild/connect-grpchealth-go/Makefile
  vendor/github.com/bufbuild/connect-grpchealth-go/README.md
  vendor/github.com/bufbuild/connect-grpchealth-go/buf.gen.yaml
  vendor/github.com/bufbuild/connect-grpchealth-go/buf.work.yaml
  vendor/github.com/bufbuild/connect-grpchealth-go/grpchealth.go
  vendor/github.com/bufbuild/connect-grpchealth-go/internal/gen/go/connectext/grpc/health/v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/modules.txt
Labels: feat

#121 #120 リフレッシュ時にauthをcacheに保存するように修正
  cmd/app/api/main.go
  internal/adapter/kvs/kvs.go
  internal/usecase/interactor/api_auth_refresh.go
  internal/usecase/interactor/api_auth_refresh_test.go
Labels: bug

#131 #130 Go1.20
  .github/workflows/lint.go.yaml
  .golangci.yaml
  Makefile
  aqua.yaml
  go.mod
  internal/adapter/controller/health.go
  internal/adapter/controller/user.go
  internal/adapter/handler/auth.go
  internal/adapter/handler/helth.go
  internal/driver/config/api_test.go
  internal/driver/config/core_test.go
  internal/usecase/interactor/api_health_check.go
  internal/usecase/interactor/core_user_create.go
Labels: chore

#134 #133 backup実行時に既存テーブルを削除
  .github/workflows/lint.go.yaml
  Makefile
  cmd/db/backup/main.go
  pkg/ent/client.go
  pkg/ent/generate.go
  pkg/ent/tx.go
Labels: bug

#139 #138 記事一覧取得を認証にて保護
  cmd/app/api/main.go
  e2e/appapi/article/list_test.go
  e2e/helper/user.go
  internal/adapter/handler/article.go
  internal/adapter/handler/article_test.go
  internal/adapter/handler/auth.go
  internal/adapter/handler/auth_test.go
  internal/adapter/handler/handler.go
  internal/adapter/handler/handler_test.go
  internal/adapter/kvs/kvs.go
  internal/application/interactor/api_article.go
  internal/application/interactor/api_article_test.go
  internal/application/interactor/api_auth.go
  internal/application/interactor/api_auth_test.go
  internal/application/usecase/api_article.go
  internal/application/usecase/api_auth.go
  internal/domain/model/auth/auth_token.go
  internal/domain/model/auth/session_token.go
  internal/domain/model/user/id.go
Labels: feat

#142 #138 記事一覧取得に認証を追加
  api/openapi.yaml
  pkg/openapi/server.gen.go
Labels: feat

#141 記事削除のproto定義、openapi定義を追加
  api/openapi.yaml
  internal/adapter/controller/article.go
  internal/adapter/handler/article.go
  pkg/connect/article/v1/article.pb.go
  pkg/connect/article/v1/articlev1connect/article.connect.go
  pkg/openapi/client.gen.go
  pkg/openapi/server.gen.go
  proto/article/v1/article.proto
Labels: feat

#143 #140 記事削除のエンドポイントを実装
  api/openapi.yaml
  e2e/appapi/article/delete_test.go
  e2e/appcore/article/delete_test.go
  internal/adapter/controller/article.go
  internal/adapter/controller/article_test.go
  internal/adapter/external/article.go
  internal/adapter/gateway/article.go
  internal/adapter/gateway/article_test.go
  internal/adapter/handler/article.go
  internal/adapter/handler/article_test.go
  internal/application/interactor/api_article.go
  internal/application/interactor/core_article.go
  internal/application/interactor/core_article_test.go
  internal/application/usecase/api_article.go
  internal/application/usecase/api_article_mock.go
  internal/application/usecase/core_article.go
  internal/application/usecase/core_article_mock.go
  internal/domain/repository/article.go
  internal/domain/repository/article_mock.go
  internal/domain/rpc/article.go
  internal/domain/rpc/article_mock.go
  pkg/connect/article/v1/article.pb.go
  pkg/connect/article/v1/articlev1connect/article.connect.go
  pkg/ent/migrate/schema.go
  pkg/ent/schema/article.go
  pkg/openapi/client.gen.go
  pkg/openapi/server.gen.go
  proto/article/v1/article.proto
Labels: feat

#147 #133 DBバックアップ処理を修正
  cmd/db/backup/main.go
Labels: bug

#155 #154 統合テストを追加
  .docker/test.docker-compose.yaml
  .env.local
  .github/workflows/lint.go.yaml
  .github/workflows/test.integration.yaml
  Makefile
  integration/external/external_test.go
  integration/gateway/gateway_test.go
  integration/helper/helper.go
  integration/helper/helper_test.go
  integration/kvs/kvs_test.go
  internal/driver/postgres/postgres.go
Labels: test

#166 #165 UserIDを伝播する
  .docker/firebase/Dockerfile
  internal/adapter/external/article.go
  internal/adapter/external/connect.go
  internal/adapter/external/health.go
  internal/adapter/external/user.go
  internal/adapter/handler/auth.go
  internal/adapter/handler/handler.go
  internal/domain/model/auth/auth_token.go
  internal/domain/model/auth/auth_token_test.go
  internal/domain/model/user.go
  internal/domain/model/user_test.go
  internal/driver/interceptor/interceptor.go
  internal/driver/middleware/middleware.go
Labels: feat

#168 #165 contextにuidを設定
  internal/adapter/handler/article.go
Labels: fix

#171 #170 KVSにトランザクションを導入
  integration/kvs/kvs_test.go
  internal/adapter/kvs/kvs.go
  internal/application/interactor/api_auth.go
  internal/application/interactor/api_auth_test.go
  internal/domain/cache/cache.go
  internal/domain/cache/cache_mock.go
Labels: feat

#185 #184 README.mdを更新
  README.md
Labels: documentation

#187 #186 認証トークンの有効期限の最大値を3600sに変更
  api/openapi.yaml
  internal/adapter/handler/auth.go
  internal/adapter/handler/auth_test.go
  internal/adapter/handler/handler_test.go
  internal/application/interactor/api_auth.go
  internal/application/interactor/api_auth_test.go
  internal/application/usecase/api_auth.go
  internal/domain/model/auth.go
  internal/domain/model/auth/auth_token.go
  internal/domain/model/auth/auth_token_test.go
  internal/domain/model/auth/expires_in.go
  internal/domain/model/auth/expires_in_test.go
  internal/domain/model/auth_test.go
Labels: fix

#193 #192 各種変数名を修正
  internal/adapter/controller/article.go
  internal/adapter/controller/article_test.go
  internal/adapter/controller/controller.go
  internal/adapter/controller/controller_test.go
  internal/adapter/controller/health.go
  internal/adapter/controller/health_test.go
  internal/adapter/controller/user.go
  internal/adapter/controller/user_test.go
  internal/adapter/external/article.go
  internal/adapter/external/auth.go
  internal/adapter/external/health.go
  internal/adapter/external/user.go
  internal/adapter/gateway/article.go
  internal/adapter/gateway/user.go
  internal/application/interactor/api_article.go
  internal/application/interactor/api_article_test.go
  internal/application/interactor/api_auth.go
  internal/application/interactor/api_auth_test.go
  internal/application/interactor/api_health.go
  internal/application/interactor/api_health_test.go
  internal/application/interactor/core_article.go
  internal/application/interactor/core_article_test.go
  internal/application/interactor/core_user.go
  internal/application/interactor/core_user_test.go
Labels: refactor
